apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-spring-basic2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-spring-basic2
    app.kubernetes.io/part-of: application-sample1
  name: devfile-sample-spring-basic2
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  - port: 1111
    targetPort: 1111
  selector:
    app: java-springboot-app
    app.kubernetes.io/instance: devfile-sample-spring-basic2
status:
  loadBalancer: {}
